### ISSUE TITLE
v. 0.7.0 error 

### ISSUE THREAD

**Issue by antonellocaroli** [HEnquist/camillagui-backend#32]
I always get this error, what can it be due to?
with version 0.6.0 there was not

![image](https://user-images.githubusercontent.com/11161093/118393570-2fbcda00-b640-11eb-8e6c-9e0a9a15287f.png)

Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/opt/camillagui/backend/views.py", line 162, in set_config
    filename = json["filename"]
KeyError: 'filename'

**Comment by JWahle** [comment]
It seems, that your pycamilladsp-plot version is not up to date. Updating it should fix that.
With an old version, I got the same error here: https://github.com/HEnquist/pycamilladsp-plot/issues/4

**Comment by antonellocaroli** [comment]
thanks, pycamilladsp-plot update, solves.

**Comment by JWahle** [comment]
Nice.
